#!/usr/bin/env python3
"""Regenerate Kitty Unicode placeholder row/column diacritics."""

import subprocess
from pathlib import Path
from urllib.request import urlopen

URL = "https://sw.kovidgoyal.net/kitty/_downloads/f0a0de9ec8d9ff4456206db8e0814937/rowcolumn-diacritics.txt"
OUTPUT = Path(__file__).parents[1] / "alacritty_terminal/src/graphics/rowcolumn_diacritics.rs"


def main() -> None:
    with urlopen(URL) as response:
        source = response.read().decode("utf-8")
    values = [
        int(line.split(";", 1)[0], 16)
        for line in source.splitlines()
        if line and not line.startswith("#")
    ]
    lines = [
        "// Generated by scripts/generate-kitty-diacritics.py from the Kitty protocol data.",
        f"pub const ROW_COLUMN_DIACRITICS: [char; {len(values)}] = [",
    ]
    for offset in range(0, len(values), 8):
        entries = ", ".join(f"'\\u{{{value:x}}}'" for value in values[offset : offset + 8])
        lines.append(f"    {entries},")
    lines.extend(
        [
            "];",
            "",
            "pub fn diacritic_index(value: char) -> Option<u16> {",
            "    ROW_COLUMN_DIACRITICS",
            "        .iter()",
            "        .position(|candidate| *candidate == value)",
            "        .and_then(|index| u16::try_from(index).ok())",
            "}",
            "",
        ]
    )
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    subprocess.run(["rustfmt", "+nightly", str(OUTPUT)], check=True)


if __name__ == "__main__":
    main()
